FROM node:20-alpine AS migrate

WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com \
    && npm install -g pnpm

COPY package.json pnpm-lock.yaml .npmrc ./

RUN pnpm config set registry https://registry.npmmirror.com \
    && pnpm install --no-frozen-lockfile

COPY prisma ./prisma

RUN pnpm prisma generate

CMD ["sh", "-c", "pnpm prisma migrate deploy && pnpm prisma db seed"]
